const mongoose = require('mongoose');

const LicenseKeySchema = new mongoose.Schema({
  key: { type: String, required: true, unique: true, uppercase: true, trim: true },
  plan: { type: String, enum: ['starter_1_99', 'pro_5_accounts', 'lifetime'], default: 'starter_1_99' },
  maxAccounts: { type: Number, default: 1 }, // 1 Gmail account per key
  isUsed: { type: Boolean, default: false },
  usedByEmail: { type: String, default: null },
  activatedAt: { type: Date, default: null },
  expiresAt: { type: Date, default: null }, // null = lifetime or auto-renew
  notes: { type: String, default: 'Generated by admin' }
}, {
  timestamps: true
});

module.exports = mongoose.models.LicenseKey || mongoose.model('LicenseKey', LicenseKeySchema);
